version: "3.7"
services: 
  microuniversidades:
    container_name: microuniversidades
    image: kevinmateo/microuniversidades:v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - ase-acad
networks:
  ase-acad:
    driver: bridge